@echo off
echo Deteniendo procesos de Node.js...
taskkill /F /IM node.exe
echo Limpiando instalacion corrupta...
rmdir /s /q node_modules
del package-lock.json
echo Reinstalando dependencias (esto puede tardar unos minutos)...
npm install
echo Iniciando aplicacion...
npm run dev
